author: GitHub User
name: Your Username

title: your awesome title
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

email: your-email@domain.com

# social links
twitter_username: anxhe_
github_username:  anxhe
# rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# baseurl: http://127.0.0.1:4000
header_pages:
  - index.md
  - blog.md

# Config section the home


# Build settings
markdown: kramdown
theme: jekyll-theme-experiment
theme_jekyll-theme-experiment:
  about:
    # title: My name
    # description: >
    #   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet urna
    #   eu dolor placerat varius. Vivamus eros augue, consequat id scelerisque nec,
    #   fringilla in est. Proin pellentesque malesuada mauris, quis aliquam augue
    #   vestibulum ac. Vestibulum ut feugiat nibh. Sed faucibus felis purus, sed
    #   convallis leo dictum vehicula.
    #   <br><br>
    #   Nam maximus tempor feugiat. Mauris tristique imperdiet nulla id egestas.
    #   Proin eget lobortis magna. Duis consectetur nibh at elit viverra congue.
    #   Ut eu turpis enim.
    avatar : https://robohash.org/experiment-avatar.png?size=300x300

  portfolio:
    title: Portfolio
    projects:
      - name: Jeckyll Theme experiment
        link: http://try.livingstyleguide.org
        github: https://github.com/fanxhe/lsg-editor
        img_relative_url: /assets/example.png

      - name: Jeckyll Theme experiment
        github: https://github.com/anxhe/jekyll-theme-experiment
        img_relative_url: /assets/example.png

      - name: Jekyll Theme experiment
        github: https://github.com/anxhe/jekyll-theme-experiment
        img_relative_url: /assets/example.png

  tools:
    - relative_url: /assets/icons/bitbucket/bitbucket-original.svg
    - relative_url: /assets/icons/heroku/heroku-original.svg
    - relative_url: /assets/icons/git/git-original.svg
    - relative_url: /assets/icons/express/express-original.svg
    - relative_url: /assets/icons/angularjs/angularjs-original.svg

exclude:
  - Gemfile
  - Gemfile.lock
