title: anxhe
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a site where I talk a litle about me and mys proyects.
# social links
twitter_username: anxhe_
github_username:  anxhe
rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# baseurl: http://127.0.0.1:4000
header_pages:
  - about.md
  - project.md
  - page.md
  - post.md

# Build settings
markdown: kramdown
theme: jekyll-theme-experiment
exclude:
  - Gemfile
  - Gemfile.lock
